name: print hello world

on:
  push:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: execute shell
        run: echo hello world
      - name: verify
        run: ls -ltra && python3 test.py
